[package]
name = "sdtp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.2.7"
tokio = { version = "1.15.0", features = ["net", "macros", "rt", "fs", "sync", "time", "io-util"] }